### ISSUE TITLE
ds1remove.ps1 not working

### ISSUE THREAD

**Issue by naidusadanala** [jimmyatSplunk/SplunkForwarderRepairKit#1]
Hi ,

I have deployed the script but its not removing actual file .

Thanks

**Comment by jimmyatSplunk** [comment]
One of the features of the script is it looks for another deploymentclient.conf in $SPLUNK_HOME/etc/apps so you don't accidentally orphan your forwarder. You can check the log in the _internal index with this query:

`index=_internal sourcetype=ds_remove:output`

**Comment by jimmyatSplunk** [comment]
There is a companion restart script that is designed to remove a file the app contains. The mechanism of the deployment server restarting the app is how the restart works. Is the app configured to restart the forwarder when an update is pushed?
