### ISSUE TITLE
Restart is not taking place when deploymentclient file is deleted

### ISSUE THREAD

**Issue by saadhasankhan** [jimmyatSplunk/SplunkForwarderRepairKit#2]
The new deploymentclient.conf file is already in the systems in etc/apps/<app>/local/deploymentclient.conf

The issue, I think, is that nothing I can see actually causes a restart. The closes thing that might is this in restart.sh

	rm -f $SPLUNK_HOME/etc/apps/SplunkForwarderRepairKit/DeleteMeToRestart

How exactly will deleting this file cause a restart is my question.

Thanks!

Saad

**Comment by jimmyatSplunk** [comment]
There is a companion restart script that is designed to remove a file the app contains. The mechanism of the deployment server restarting the app is how the restart is meant to work. Is the app configured to restart the forwarder when an update is pushed?

**Comment by saadhasankhan** [comment]
Thank you for your response. Yes the app is configured to restart the forwarders when an update is pushed.

What is happening is that the restart happens at the beginning, when the app is deployed. The DeleteMeToRestart file is deleted later when the app has already restarted. Another restart is required. 

Since posting my question, research on various splunk forums shows that supposedly the forwarder will check the hash of the local copy of the app with the hash on the deployment server. Since DeleteMeToRestart is deleted locally, the hash would be different than the deployment server's hash for the app, at which point the forwarder would theoretically get a new version of the app, prompting a second restart, and this time the change will take.

In practice I cannot see this happening. What I had to do was to deploy an empty app after deploying  the SplunkForwarderRepairKit to initiate a second restart. This worked.

Would be grateful for you thoughts on what I observed. Perhaps it had to do with the forwarder versions. The forwarders in my environment were 6.5.2 and I did not check with 7.x or 8.x forwarders.

Thanks! Saad

**Comment by jimmyatSplunk** [comment]
I'd be interested to see the btool output for the app deployment from th deployment server.

`$SPLUNK_HOME/bin/splunk btool serverclass list serverClass:className:app:appName --debug`

**Comment by jimmyatSplunk** [comment]
I've made a modification to the logic of the deployment server removal script to better determine when it's appropriate to remove the local file and hopefully produce better results.

**Comment by saadhasankhan** [comment]
I apologize for missing your previous comment.

Here is the btool output

`[splunk@splunk_prod1_cengage_deployer ~]$ bin/splunk btool serverclass list serverClass:cengage_all:app:cengage_deploymentclient_config --debug
/opt/splunk/etc/system/local/serverclass.conf [serverClass:cengage_all:app:cengage_deploymentclient_config]
/opt/splunk/etc/system/local/serverclass.conf restartSplunkWeb = 0
/opt/splunk/etc/system/local/serverclass.conf restartSplunkd = 1
/opt/splunk/etc/system/local/serverclass.conf stateOnClient = enabled`

**Comment by jimmyatSplunk** [comment]
Ah I see it now. Because the `restart.sh` and `restart.ps1` scripts hardcode the directory of the app, it's not able to perform the proper deletion. I either need to modify the scripts so it detects the new parent app's name or you'll need to deploy the "SplunkForwarderRepairKit" app so the file can be appropriately deleted.

To get it working (for now) I would deploy the "SplunkForwarderRepairKit" without the "inputs.conf" with the `restartSplunkd` flag set to 1 for the app. This will allow the app to work properly until I can work on having the restart scripts generate their own app context.

**Comment by jimmyatSplunk** [comment]
Hey @saadhasankhan,

I have made some adjustments to the code in the "develop" branch of this repo. Perhaps you may try to utilize that and see if it gives you desired result.

https://github.com/jimmyatSplunk/SplunkForwarderRepairKit/tree/develop

**Comment by saadhasankhan** [comment]
Thank you. Will use next time need occurs and let you know. Saad
